apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "helm-flask-app.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "helm-flask-app.fullname" . }}-service
                port:
                  number: 5000