apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-flask-app.fullname" . }}-service
  labels:
    {{- include "helm-flask-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: flask-app-http
  selector:
    {{- include "helm-flask-app.selectorLabels" . | nindent 4 }}
